server:
  port: 8181

spring:
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: calculatrice-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/calcul/**
        - id: calculstatistique-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/stats/**
        - id: calculstatistique-feign-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/feign/stats/**